name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: macos-15
    permissions:
      contents: read
    timeout-minutes: 30
    strategy:
      matrix:
        test-type: [unit, build]
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          setup_ruby: true
          setup_mint: false

      - name: Run Tests
        run: just ${{ matrix.test-type }}-test
